# -*- coding: utf-8 -*-
"""LAB2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AQ5g8dHFl4rb0mfEgGqNfp39Sh1UbJvz

# New Section

# 1.**Lists**
"""

my_list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
print(my_list)

list_sum = sum(my_list)
list_min = min(my_list)
list_max = max(my_list)

print(f"Sum: {list_sum}")
print(f"Minimum: {list_min}")
print(f"Maximum: {list_max}")

# Sort the list in ascending order
my_list.sort()
print(f"List sorted in ascending order: {my_list}")

# Sort the list in descending order
my_list.sort(reverse=True)
print(f"List sorted in descending order: {my_list}")

my_list.append(11)
print(f"List after appending 11: {my_list}")

if len(my_list) > 0:
  removed_element = my_list.pop(0)
  print(f"List after removing {removed_element}: {my_list}")
else:
  print("List is empty, cannot remove element.")

"""# 2.**Tuples**"""

fruits_tuple = ("apple", "banana", "cherry", "date", "elderberry")
print(fruits_tuple)

second_element = fruits_tuple[1]
print(f"The second element of the tuple is: {second_element}")

fruits_list = list(fruits_tuple)
print(f"Converted to list: {fruits_list}")

fruits_list.append("fig")
print(f"List after appending 'fig': {fruits_list}")

fruits_list.remove("banana")
print(f"List after removing 'banana': {fruits_list}")

modified_fruits_tuple = tuple(fruits_list)
print(f"Converted back to tuple: {modified_fruits_tuple}")

"""## 3.**Sets**"""

set1 = {1, 2, 3, 4, 5}
set2 = {4, 5, 6, 7, 8}

print(f"Set 1: {set1}")
print(f"Set 2: {set2}")

set_union = set1.union(set2)
print(f"Union of Set 1 and Set 2: {set_union}")

set_intersection = set1.intersection(set2)
print(f"Intersection of Set 1 and Set 2: {set_intersection}")

set_difference1 = set1.difference(set2)
print(f"Difference (Set1 - Set2): {set_difference1}")

set_difference2 = set2.difference(set1)
print(f"Difference (Set2 - Set1): {set_difference2}")

"""# 4.**Dictionaries**"""

student_marks = {
    "Ali": 85,
    "Babar": 92,
    "Ahmad": 78,
    "Zain": 95,
    "Mohid": 88
}

print("Initial dictionary:")
print(student_marks)

print("\nKeys in the dictionary:")
for key in student_marks.keys():
    print(key)

print("\nValues in the dictionary:")
for value in student_marks.values():
    print(value)

print("\nKey-value pairs in the dictionary:")
for key, value in student_marks.items():
    print(f"{key}: {value}")

student_marks["Ali"] = 90
print("\nDictionary after updating Ali's marks:")
print(student_marks)

del student_marks["Ahmad"]
print("\nDictionary after deleting Ahmad:")
print(student_marks)

key_to_check = "Zain"
if key_to_check in student_marks:
    print(f"\n'{key_to_check}' exists in the dictionary.")
else:
    print(f"\n'{key_to_check}' does not exist in the dictionary.")

key_to_check = "Ahmad"
if key_to_check in student_marks:
    print(f"\n'{key_to_check}' exists in the dictionary.")
else:
    print(f"\n'{key_to_check}' does not exist in the dictionary.")

"""# 5.**Numpy**

# 6.**Matplotlib**
"""